# Generated by Django 4.1.1 on 2022-09-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_adds',
            field=models.CharField(default='', max_length=100),
        ),
    ]
