# Generated by Django 4.1.1 on 2022-09-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='sell_email',
            new_name='seller_email',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sell_image',
            new_name='seller_image',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sell_name',
            new_name='seller_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sell_password',
            new_name='seller_password',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sell_phone',
            new_name='seller_phone',
        ),
    ]
