# Generated by Django 4.1.1 on 2022-10-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_admin_admins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_adds',
        ),
    ]
